% Definitions from glut.h

% Display mode bit mask
kGLUT_RGB(0).
kGLUT_RGBA(0).
kGLUT_INDEX(1).
kGLUT_SINGLE(0).
kGLUT_DOUBLE(2).
kGLUT_ACCUM(4).
kGLUT_ALPHA(8).
kGLUT_DEPTH(16).
kGLUT_STENCIL(32).
kGLUT_MULTISAMPLE(128).
kGLUT_STEREO(256).
kGLUT_LUMINANCE(512).
kGLUT_NO_RECOVERY(1024).


% Mouse Buttons
kGLUT_LEFT_BUTTON(0).
kGLUT_MIDDLE_BUTTON(1).
kGLUT_RIGHT_BUTTON(2).


% Mouse Button State
kGLUT_UP(0).
kGLUT_DOWN(1).


% Function Keys
kGLUT_KEY_F1(1).
kGLUT_KEY_F2(2).
kGLUT_KEY_F3(3).
kGLUT_KEY_F4(4).
kGLUT_KEY_F5(5).
kGLUT_KEY_F6(6).
kGLUT_KEY_F7(7).
kGLUT_KEY_F8(8).
kGLUT_KEY_F9(9).
kGLUT_KEY_F10(10).
kGLUT_KEY_F11(11).
kGLUT_KEY_F12(12).
kGLUT_KEY_LEFT(100).
kGLUT_KEY_UP(101).
kGLUT_KEY_RIGHT(102).
kGLUT_KEY_DOWN(103).
kGLUT_KEY_PAGE_UP(104).
kGLUT_KEY_PAGE_DOWN(105).
kGLUT_KEY_HOME(106).
kGLUT_KEY_END(107).
kGLUT_KEY_INSERT(108).

% Entry/exit  state
kGLUT_LEFT(0).
kGLUT_ENTERED(1).

% Menu usage  state
kGLUT_MENU_NOT_IN_USE(0).
kGLUT_MENU_IN_USE(1).

% Visibility  state
kGLUT_NOT_VISIBLE(0).
kGLUT_VISIBLE(1).

% Window status  state
kGLUT_HIDDEN(0).
kGLUT_FULLY_RETAINED(1).
kGLUT_PARTIALLY_RETAINED(2).
kGLUT_FULLY_COVERED(3).

% Color index component selection values
kGLUT_RED(0).
kGLUT_GREEN(1).
kGLUT_BLUE(2).

% Layers for use
kGLUT_NORMAL(0).
kGLUT_OVERLAY(1).

% glutGet parameters
kGLUT_WINDOW_X(100).
kGLUT_WINDOW_Y(101).
kGLUT_WINDOW_WIDTH(102).
kGLUT_WINDOW_HEIGHT(103).
kGLUT_WINDOW_BUFFER_SIZE(104).
kGLUT_WINDOW_STENCIL_SIZE(105).
kGLUT_WINDOW_DEPTH_SIZE(106).
kGLUT_WINDOW_RED_SIZE(107).
kGLUT_WINDOW_GREEN_SIZE(108).
kGLUT_WINDOW_BLUE_SIZE(109).
kGLUT_WINDOW_ALPHA_SIZE(110).
kGLUT_WINDOW_ACCUM_RED_SIZE(111).
kGLUT_WINDOW_ACCUM_GREEN_SIZE(112).
kGLUT_WINDOW_ACCUM_BLUE_SIZE(113).
kGLUT_WINDOW_ACCUM_ALPHA_SIZE(114).
kGLUT_WINDOW_DOUBLEBUFFER(115).
kGLUT_WINDOW_RGBA(116).
kGLUT_WINDOW_PARENT(117).
kGLUT_WINDOW_NUM_CHILDREN(118).
kGLUT_WINDOW_COLORMAP_SIZE(119).
kGLUT_WINDOW_NUM_SAMPLES(120).
kGLUT_WINDOW_STEREO(121).
kGLUT_WINDOW_CURSOR(122).
kGLUT_SCREEN_WIDTH(200).
kGLUT_SCREEN_HEIGHT(201).
kGLUT_SCREEN_WIDTH_MM(202).
kGLUT_SCREEN_HEIGHT_MM(203).
kGLUT_MENU_NUM_ITEMS(300).
kGLUT_DISPLAY_MODE_POSSIBLE(400).
kGLUT_INIT_WINDOW_X(500).
kGLUT_INIT_WINDOW_Y(501).
kGLUT_INIT_WINDOW_WIDTH(502).
kGLUT_INIT_WINDOW_HEIGHT(503).
kGLUT_INIT_DISPLAY_MODE(504).
kGLUT_ELAPSED_TIME(700).
kGLUT_WINDOW_FORMAT_ID(123).


% glutDeviceGet parameters
kGLUT_HAS_KEYBOARD(600).
kGLUT_HAS_MOUSE(601).
kGLUT_HAS_SPACEBALL(602).
kGLUT_HAS_DIAL_AND_BUTTON_BOX(603).
kGLUT_HAS_TABLET(604).
kGLUT_NUM_MOUSE_BUTTONS(605).
kGLUT_NUM_SPACEBALL_BUTTONS(606).
kGLUT_NUM_BUTTON_BOX_BUTTONS(607).
kGLUT_NUM_DIALS(608).
kGLUT_NUM_TABLET_BUTTONS(609).
kGLUT_DEVICE_IGNORE_KEY_REPEAT(610).
kGLUT_DEVICE_KEY_REPEAT(611).
kGLUT_HAS_JOYSTICK(612).
kGLUT_OWNS_JOYSTICK(613).
kGLUT_JOYSTICK_BUTTONS(614).
kGLUT_JOYSTICK_AXES(615).
kGLUT_JOYSTICK_POLL_RATE(616).


% glutLayerGet parameters
kGLUT_OVERLAY_POSSIBLE(800).
kGLUT_LAYER_IN_USE(801).
kGLUT_HAS_OVERLAY(802).
kGLUT_TRANSPARENT_INDEX(803).
kGLUT_NORMAL_DAMAGED(804).
kGLUT_OVERLAY_DAMAGED(805).


% glutVideoResizeGet parameters
kGLUT_VIDEO_RESIZE_POSSIBLE(900).
kGLUT_VIDEO_RESIZE_IN_USE(901).
kGLUT_VIDEO_RESIZE_X_DELTA(902).
kGLUT_VIDEO_RESIZE_Y_DELTA(903).
kGLUT_VIDEO_RESIZE_WIDTH_DELTA(904).
kGLUT_VIDEO_RESIZE_HEIGHT_DELTA(905).
kGLUT_VIDEO_RESIZE_X(906).
kGLUT_VIDEO_RESIZE_Y(907).
kGLUT_VIDEO_RESIZE_WIDTH(908).
kGLUT_VIDEO_RESIZE_HEIGHT(909).


% glutGetModifiers return mask
kGLUT_ACTIVE_SHIFT(1).
kGLUT_ACTIVE_CTRL(2).
kGLUT_ACTIVE_ALT(4).

% glutSetCursor parameters
% Basic arrows
kGLUT_CURSOR_RIGHT_ARROW(0).
kGLUT_CURSOR_LEFT_ARROW(1).

% Symbolic cursor shapes
kGLUT_CURSOR_INFO(2).
kGLUT_CURSOR_DESTROY(3).
kGLUT_CURSOR_HELP(4).
kGLUT_CURSOR_CYCLE(5).
kGLUT_CURSOR_SPRAY(6).
kGLUT_CURSOR_WAIT(7).
kGLUT_CURSOR_TEXT(8).
kGLUT_CURSOR_CROSSHAIR(9).

% Directional cursors
kGLUT_CURSOR_UP_DOWN(10).
kGLUT_CURSOR_LEFT_RIGHT(11).

% Sizing cursors
kGLUT_CURSOR_TOP_SIDE(12).
kGLUT_CURSOR_BOTTOM_SIDE(13).
kGLUT_CURSOR_LEFT_SIDE(14).
kGLUT_CURSOR_RIGHT_SIDE(15).
kGLUT_CURSOR_TOP_LEFT_CORNER(16).
kGLUT_CURSOR_TOP_RIGHT_CORNER(17).
kGLUT_CURSOR_BOTTOM_RIGHT_CORNER(18).
kGLUT_CURSOR_BOTTOM_LEFT_CORNER(19).

% Inherit from parent window
kGLUT_CURSOR_INHERIT(100).

% Blank cursor
kGLUT_CURSOR_NONE(101).

% Fullscreen crosshair (if available)
kGLUT_CURSOR_FULL_CROSSHAIR(102).

